In [2]:
!pip install numpy --upgrade

Defaulting to user installation because normal site-packages is not writeable


In [3]:
import numpy as np

In [8]:
array_one = np.array([0,1,3,5,7,9])
array_one

array([0, 1, 3, 5, 7, 9])

In [9]:
#Creating array based on a list
num = [11,22,33,44,55,66,77]
array_two = np.array(num)
array_two

array([11, 22, 33, 44, 55, 66, 77])

In [10]:
#Creating one array of 2 rows and 3 columns whose elements are all zero
array_of_zeroes = np.zeros((2,3))
array_of_zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
#Creating one array of 3 rows and 2 columns whose elements are all 1
array_of_ones = np.ones((3,2))
array_of_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
#Creating one array of 3 rows and 2 columns whose elements are all 1, and the data type is integer
array_of_ones = np.ones((3,2), dtype = np.int32)
array_of_ones

array([[1, 1],
       [1, 1],
       [1, 1]])

In [14]:
array_empty = np.empty((3,2))
array_empty

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
#Creating an array of elements, beginning in  2 until number 24 is reached, incrementing by 2
array_of_evens = np.arange(2,24,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [17]:
array_of_floats = np.arange(1,3,0.3)
array_of_floats

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8])

In [23]:
array_2D = np.array([(3, 4, 6),(2, 1, 6)])
array_2D

array([[3, 4, 6],
       [2, 1, 6]])

In [24]:
array_2D.shape

(2, 3)

In [25]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [26]:
array_nd = np.arange(8).reshape(2,4)
array_nd

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [27]:
 array_nd

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [28]:
array_ones = np.ones_like(array_nd)
array_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])