In [12]:
#Create an array x of the same shape as another array y with all elements set to 1
import numpy as np
x = np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
#Retrieve the last 20 rows and the second to fifth columns of a 2-D array
x = np.arange(200).reshape(25,8)
x[-20:,1:6]


array([[ 41,  42,  43,  44,  45],
       [ 49,  50,  51,  52,  53],
       [ 57,  58,  59,  60,  61],
       [ 65,  66,  67,  68,  69],
       [ 73,  74,  75,  76,  77],
       [ 81,  82,  83,  84,  85],
       [ 89,  90,  91,  92,  93],
       [ 97,  98,  99, 100, 101],
       [105, 106, 107, 108, 109],
       [113, 114, 115, 116, 117],
       [121, 122, 123, 124, 125],
       [129, 130, 131, 132, 133],
       [137, 138, 139, 140, 141],
       [145, 146, 147, 148, 149],
       [153, 154, 155, 156, 157],
       [161, 162, 163, 164, 165],
       [169, 170, 171, 172, 173],
       [177, 178, 179, 180, 181],
       [185, 186, 187, 188, 189],
       [193, 194, 195, 196, 197]])

In [55]:
#Recall the 2 main ways in which a 2-D array can be flattened to a 1-D array
x = np.arange(200).reshape(25,8)
x.ravel()
x.flatten()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18