In [1]:
import numpy as np

In [2]:
x = np.array([2,4,6,8,10])
y = np.array([5,5,5,5,5])

In [3]:
x * y

array([10, 20, 30, 40, 50])

In [4]:
z = 10

In [5]:
x * z

array([ 20,  40,  60,  80, 100])

In [6]:
ones = np.ones((3,4))

In [7]:
ones * z

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [8]:
top_speeds = [184, 243, 192, 309, 257, 218]
weights = [1178, 1243, 1243, 1047, 1673, 1475]

In [9]:
car_info = np.array([top_speeds, weights])

car_info

array([[ 184,  243,  192,  309,  257,  218],
       [1178, 1243, 1243, 1047, 1673, 1475]])

In [10]:
conversion_factors = np.array([0.621371, 2.20462])

conversion_factors

array([0.621371, 2.20462 ])

In [11]:
conversion_factors.shape

(2,)

In [12]:
car_info.shape

(2, 6)

In [13]:
car_info * conversion_factors

ValueError: operands could not be broadcast together with shapes (2,6) (2,) 

In [14]:
new_factors = conversion_factors.reshape(2,1)
new_factors

array([[0.621371],
       [2.20462 ]])

In [17]:
new_factors.shape

(2, 1)

In [18]:
car_info * new_factors

array([[ 114.332264,  150.993153,  119.303232,  192.003639,  159.692347,
         135.458878],
       [2597.04236 , 2740.34266 , 2740.34266 , 2308.23714 , 3688.32926 ,
        3251.8145  ]])