In [1]:
import numpy as np

In [3]:
x = np.arange(12).reshape(3,4)

In [4]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
index_bool = x > 6

In [6]:
index_bool

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [8]:
x[index_bool]

array([ 7,  8,  9, 10, 11])

In [9]:
print(x[x > 6])

[ 7  8  9 10 11]


In [10]:
x < 7

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False, False]])

In [11]:
np.count_nonzero(x < 7)

7

In [12]:
np.sum(x < 7, axis = 1)

array([4, 3, 0])

In [13]:
np.any(x > 8)

True

In [14]:
np.all(x < 11)

False

In [15]:
np.all(x < 50)

True

In [16]:
np.all(x < 10, axis = 1)

array([ True,  True, False])